# Generated by Django 5.2.4 on 2025-08-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='products/')),
                ('category', models.CharField(choices=[('dresses', 'Dresses'), ('scarves', 'Scarves'), ('bags', 'Bags'), ('shirts', 'Shirts'), ('jeans', 'Jeans'), ('sweaters', 'Sweaters'), ('sleeves', 'Sleeves'), ('beanies', 'Beanies'), ('caps', 'Caps'), ('knitwear', 'Knitwear')], max_length=20)),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
